text="アイスランド語Icelandicアゼルバイジャン語Azeerbaijaniアフリカーンス語Afrikaansアムハラ語Amharicアラビア語Arabicアルバニア語Albanianアルメニア語Armenianイタリア語Italianインドネシア語Indonesianウクライナ語Ukrainianウズベク語Uzbekウルドゥー語Urdu英語Englishエストニア語Estonianオランダ語Dutchカタルーニャ語Catalanガリシア語Galician韓国語Korean広東語Cantoneseカンナダ語Kannadaギリシャ語Greekグジャラート語Gujaratiクメール語Khmerクロアチア語Croatianジャワ語Javaneseジョージア語Georgianシンハラ語Sinhalaスウェーデン語Swedishズールー語Zuluスペイン語Spanishスロバキア語Slovakスロベニア語Slovenianスワヒリ語Swahiliスンダ語Sundaneseセルビア語Serbianタイ語Thaiタミル語Tamilチェコ語Czech中国語Chineseテルグ語Teluguデンマーク語Danishドイツ語Germanトルコ語Turkish日本語Japaneseネパール語Nepaliノルウェー語Norwegianバスク語Basqueハンガリー語Hungarianバンジャーブ語Panjabiヒンディー語Hindiフィリピノ語Filipinoフィンランド語Finnishフランス語Frenchブルガリア語Bulgarianベトナム語Vietnameseヘブライ語Hebrewペルシャ語Persianベンガル語Bengaliポーランド語Polishボスニア語Bosnianポルトガル語Portugueseマケドニア語Macedonianマラーティー語Marathiマラヤーラム語Malayalamマレー語Malayミャンマー語Burmeseモンゴル語Mongolianラオ語Laoラトビア語Latvianリトアニア語Lithuanianルーマニア語Romanianロシア語Russian"




en_languages = text.scan(/\w+/)
  
p en_languages
p en_languages.count

jp_languages = text.scan(/\W+語/)
  
p jp_languages
p jp_languages.count